version: '3.8'

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - "9000:5432"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules/
      - ./server:/app/
    env_file:
      - docker.env
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      # dockerfile: Dockerfile.dev FOR DEV PORPOUSE
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules/
      - ./client:/app/
    depends_on:
      - server
    stdin_open: true
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - client
    ports:
      - "3050:80"